# Generated by Django 4.0.3 on 2022-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='religion',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
